apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: go-quickstart.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Memcached is the Schema for the memcacheds API
      displayName: Memcached
      kind: Memcached
      name: memcacheds.cache.example.com
      specDescriptors:
      - displayName: Val Test
        path: valTest
      - displayName: Val
        path: val
      - description: Represents the current applications current replica size.
        displayName: Number of pods
        path: size
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:podCount
        - urn:alm:descriptor:io.kubernetes:custom
      statusDescriptors:
      - description: Status of the ELM Instance Deployment created and managed by
          it
        displayName: Deployment Status
        path: deploymentStatus
      - description: Represents the latest available observations of a deployment's
          current state.
        displayName: Creation Events
        path: deploymentStatus.conditions
        x-descriptors:
        - urn:alm:descriptor:io.kubernetes.conditions
      - description: ApplicationsStatus Status of the ELM applications
        displayName: Applications Status
        path: applicationsStatus
      - description: Represents the latest available observations of applications
          current state.
        displayName: Applications Events
        path: applicationsStatus.conditions
        x-descriptors:
        - urn:alm:descriptor:io.kubernetes.conditions
      - description: Status of the ELM Instance Upgrade
        displayName: Upgrade Status
        path: upgradeStatus
      - description: Represents the latest available observations of an upgrade state.
        displayName: Upgrade Events
        path: upgradeStatus.conditions
        x-descriptors:
        - urn:alm:descriptor:io.kubernetes.conditions
      - description: List of conditions, a history of state transitions
        displayName: Conditions
        path: conditions
        x-descriptors:
        - urn:alm:descriptor:io.kubernetes.conditions
      version: v1alpha1
  description: memcached Operator with statusDescriptors for testing conditions widget
    ordering
  displayName: memcached Operator with statusDescriptors
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - memcached
  - descriptors
  links:
  - name: Go Quickstart
    url: https://go-quickstart.domain
  maturity: alpha
  provider:
    name: tw
  version: 0.0.0
